version: "3.9"

services:
  db:
    container_name: upydb
    image: mariadb:latest
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: tf4CcEuN3dENXLgs
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      MARIADB_DATABASE: youpie
      MARIADB_USER: youpie
      MARIADB_PASSWORD: tf4CcEuN3dENXLgs