version: "3.9"

services:
  db:
    container_name: upydb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tf4CcEuN3dENXLgs
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      MYSQL_DATABASE: youpie
      MYSQL_USER: youpie
      MYSQL_PASSWORD: tf4CcEuN3dENXLgs
    volumes:
      - ./configs/conf.d:/etc/mysql/conf.d:ro